language: go

go:
  - "1.12.x"

script:
  - go test -v -covermode=count -coverprofile=coverage.out ./...

after_success:
  - goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
  - bash <(curl -s https://codecov.io/bash) -f coverage.out
